// Generated by CoffeeScript 1.6.3
(function() {
  var wpt_tickets;

  wpt_tickets = (function() {
    function wpt_tickets() {
      var _this = this;
      this.ticket_urls = jQuery('.wpt_tickets_url').click(function(e) {
        return _this.tickets(e.currentTarget);
      });
    }

    wpt_tickets.prototype.tickets = function(e) {
      var tickets_url, tmp_parts, url, url_anchor, url_base, url_parts, url_query;
      tickets_url = jQuery(e);
      if (tickets_url.hasClass('wp_theatre_integrationtype_new_window')) {
        window.open(tickets_url.attr('href'));
        return false;
      }
      if (tickets_url.hasClass('wp_theatre_integrationtype_lightbox')) {
        url = tickets_url.attr('href');
        if (url.indexOf('#')) {
          tmp_parts = url.split('#');
          url = tmp_parts[0];
          url_anchor = tmp_parts[1];
        }
        if (url.indexOf('?')) {
          url_parts = url.split('?');
          url_base = url_parts[0];
          url_query = url_parts[1];
        } else {
          url_base = url;
        }
        if (url_query) {
          url_query += '&';
        }
        url_query += 'TB_iframe=true&width=800&height=600';
        url = url_base + '?' + url_query;
        if (url_anchor) {
          url += '#' + url_anchor;
        }
        tb_show('', url);
        return false;
      }
      return true;
    };

    return wpt_tickets;

  })();

  jQuery(function() {
    return wpt_tickets = new wpt_tickets;
  });

}).call(this);
