// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(function() {
    /*
    	Enable datepicker in event admin form.
    */

    jQuery('.wp_theatre_datepicker').datetimepicker({
      dateFormat: 'yy-mm-dd',
      timeFormat: 'HH:mm:ss'
    });
    /*
    	Update all connected events when bulk updating productions.
    	See: http://codex.wordpress.org/Plugin_API/Action_Reference/bulk_edit_custom_box
    */

    return jQuery('#bulk_edit').live('click', function() {
      var bulk_row, post_ids, post_status;
      bulk_row = jQuery('#bulk-edit');
      post_ids = new Array();
      bulk_row.find('#bulk-titles').children().each(function() {
        return post_ids.push(jQuery(this).attr('id').replace(/^(ttle)/i, ''));
      });
      post_status = bulk_row.find('select[name="_status"]').val();
      return jQuery.ajax({
        url: ajaxurl,
        type: 'POST',
        async: false,
        cache: false,
        data: {
          action: 'save_bulk_edit_wp_theatre_prod',
          post_ids: post_ids,
          post_status: post_status
        }
      });
    });
  });

}).call(this);
